import type { Restaurant, RestaurantWithMenu } from '@/types';

// Mock data for development/demo when API is not available
export const mockRestaurants: Restaurant[] = [
  {
    id: '1',
    name: 'The Spice Garden',
    description: 'Authentic Indian cuisine with a modern twist. Famous for our biryanis and tandoori specialties.',
    cuisine: 'Indian',
    rating: 4.5,
    deliveryTime: '25-35 min',
    priceRange: '$$',
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop',
    isOpen: true,
    address: '123 Curry Lane, Food District',
    lat: 12.9716,
    lng: 77.5946,
  },
  {
    id: '2',
    name: 'Pizza Paradise',
    description: 'Wood-fired pizzas made with imported Italian ingredients. Thin crust perfection.',
    cuisine: 'Italian',
    rating: 4.3,
    deliveryTime: '30-40 min',
    priceRange: '$$',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop',
    isOpen: true,
    address: '456 Margherita Ave',
    lat: 12.9756,
    lng: 77.5906,
  },
  {
    id: '3',
    name: 'Dragon Wok',
    description: 'Szechuan and Cantonese favorites. Quick stir-fries and dim sum delights.',
    cuisine: 'Chinese',
    rating: 4.1,
    deliveryTime: '20-30 min',
    priceRange: '$',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&h=300&fit=crop',
    isOpen: false,
    address: '789 Noodle Street',
    lat: 12.9686,
    lng: 77.5986,
  },
  {
    id: '4',
    name: 'Burger Barn',
    description: 'Juicy handcrafted burgers with premium beef. Crispy fries and thick shakes.',
    cuisine: 'American',
    rating: 4.6,
    deliveryTime: '15-25 min',
    priceRange: '$$',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    isOpen: true,
    address: '321 Grill Road',
    lat: 12.9796,
    lng: 77.5866,
  },
  {
    id: '5',
    name: 'Sushi Zen',
    description: 'Fresh sashimi and creative maki rolls. Omakase experience at home.',
    cuisine: 'Japanese',
    rating: 4.8,
    deliveryTime: '35-45 min',
    priceRange: '$$$',
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=300&fit=crop',
    isOpen: true,
    address: '555 Sakura Boulevard',
    lat: 12.9656,
    lng: 77.6026,
  },
  {
    id: '6',
    name: 'Taco Fiesta',
    description: 'Street-style Mexican tacos and burritos. Spicy, fresh, and full of flavor.',
    cuisine: 'Mexican',
    rating: 4.2,
    deliveryTime: '20-30 min',
    priceRange: '$',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop',
    isOpen: true,
    address: '888 Salsa Street',
    lat: 12.9736,
    lng: 77.5886,
  },
];

export const getMockRestaurantWithMenu = (id: string): RestaurantWithMenu | null => {
  const restaurant = mockRestaurants.find(r => r.id === id);
  if (!restaurant) return null;

  return {
    restaurant,
    menu: [
      {
        id: `${id}-cat-1`,
        name: 'Starters',
        menuItems: [
          {
            id: `${id}-1`,
            name: 'Crispy Spring Rolls',
            description: 'Golden fried rolls stuffed with vegetables',
            price: 149,
            category: 'Starters',
            isVeg: true,
            isAvailable: true,
          },
          {
            id: `${id}-2`,
            name: 'Chicken Wings',
            description: 'Spicy buffalo wings with ranch dip',
            price: 249,
            category: 'Starters',
            isVeg: false,
            isAvailable: true,
          },
          {
            id: `${id}-3`,
            name: 'Soup of the Day',
            description: 'Chef\'s special soup served hot',
            price: 99,
            category: 'Starters',
            isVeg: true,
            isAvailable: true,
          },
        ],
      },
      {
        id: `${id}-cat-2`,
        name: 'Main Course',
        menuItems: [
          {
            id: `${id}-4`,
            name: 'Signature Special',
            description: 'Our house specialty prepared with love',
            price: 449,
            category: 'Main Course',
            isVeg: false,
            isAvailable: true,
          },
          {
            id: `${id}-5`,
            name: 'Vegetarian Delight',
            description: 'Fresh seasonal vegetables in chef\'s sauce',
            price: 349,
            category: 'Main Course',
            isVeg: true,
            isAvailable: true,
          },
          {
            id: `${id}-6`,
            name: 'Grilled Protein Bowl',
            description: 'Healthy bowl with grains and grilled protein',
            price: 399,
            category: 'Main Course',
            isVeg: false,
            isAvailable: false,
          },
        ],
      },
      {
        id: `${id}-cat-3`,
        name: 'Desserts',
        menuItems: [
          {
            id: `${id}-7`,
            name: 'Chocolate Brownie',
            description: 'Warm brownie with vanilla ice cream',
            price: 179,
            category: 'Desserts',
            isVeg: true,
            isAvailable: true,
          },
          {
            id: `${id}-8`,
            name: 'Fresh Fruit Bowl',
            description: 'Seasonal fruits with honey drizzle',
            price: 129,
            category: 'Desserts',
            isVeg: true,
            isAvailable: true,
          },
        ],
      },
      {
        id: `${id}-cat-4`,
        name: 'Beverages',
        menuItems: [
          {
            id: `${id}-9`,
            name: 'Fresh Lime Soda',
            description: 'Refreshing lime with soda water',
            price: 69,
            category: 'Beverages',
            isVeg: true,
            isAvailable: true,
          },
          {
            id: `${id}-10`,
            name: 'Mango Lassi',
            description: 'Creamy yogurt drink with mango',
            price: 99,
            category: 'Beverages',
            isVeg: true,
            isAvailable: true,
          },
        ],
      },
    ],
  };
};
